Traceback (most recent call last):
  File "ml/classifier.py", line 8, in <module>
    photoId = sys.argv[2]
IndexError: list index out of range
